### ISSUE TITLE
All course folders are nested. File structure is different

### ISSUE THREAD

**Issue by JohnnyLAmpAz** [rssws/moodle-dl-ext#17]
First of all thanks for the extension. It can take all the files from a certain course and that's awesome.
The problem here is that the folders at the course root end up to be nested to each other instead of being in the same directory. And also, some files of respective folders are placed inside wrong folder.

Here a screenshot:
![image](https://user-images.githubusercontent.com/29355695/201540896-a0dcf94b-0ef4-4e64-957b-808151c1b08a.png)

**Comment by rssws** [comment]
Hi @JohnnyLAmpAz ,

Thanks for reporting the issue. I assume the problem would be that inside the page of a folder, there is another folder link. So the extension will keep crawling into that folder, and thus, think that one should contain the other. 

You can verify this if you go to `https://<your-moodle>/course/resources.php?id=<course-id>`, which is used as the entry point for crawling. 

But as I haven't had this situation yet, it is quite hard for me to reproduce the error and write a fix for it. A potential solution would be to crawl only links within a specific HTML element.

If you want to contribute, I am happy to provide you with some help.

**Comment by JohnnyLAmpAz** [comment]
For sure, I want to help you as I can, I'm not that skilled tho. With a bit of help I would be proud to make my first contribution to a project 😊.

I made some screenshots and grabbed some HTML to give you more info.

## Course view page

In my specific case my course apparently is divided in _sections_ and appear on the left panel as folders, but indeed they are just sections in the course page, indexed by the id `#section-0`, `#section-1` etc...

Look here:
![course-view](https://user-images.githubusercontent.com/29355695/201762976-91ea71bc-6ebd-48c2-956a-3ca7ab422ae5.jpg)

## Resources view page

In the resources pages sections appear to be separated by an empty row, inside of which there is a `div.tabledivider`  element and the row of the first resource of that section includes the section name in the first cell, otherwise it's empty.
![resources](https://user-images.githubusercontent.com/29355695/201763020-00de4af7-06d3-4d80-823c-862cdc188897.jpg)

## HTML source

Uploaded some relevant sections [on Pastebin](https://pastebin.com/qU0Ja4xx).

## The goal

In this case sections are not really folders but it would be nice to make a separate directory inside the zip for each. In my specific case there are tons of exams essays PDF files, it's a mess without separating them.

**Comment by rssws** [comment]
Hi @JohnnyLAmpAz ,

I think I might have a clue about why the bug is happening. I created a new PR #18  for this issue. You can build it locally using `yarn package` and then load the extension from the `output` folder as mentioned in the `README.md`. Please let me know if you encounter any problems.

Besides, your idea of using the section name as the folder name could potentially work. But since moodles from different schools or institutions can vary a lot with respect to the page structure and content, it could be hard to use a section name as a proper folder name. For example, some courses in my university have dates as section names such as `18. Januar - 24. Januar`. Therefore, I personally feel it is hard to find a good general solution.

**Comment by JohnnyLAmpAz** [comment]
I was also thinking about different schools layouts, it probably is like you said.
You fixed it real quick, in the end I just raised this issue 😅.

**Comment by rssws** [comment]
> I was also thinking about different schools layouts, it probably is like you said. You fixed it real quick, in the end I just raised this issue 😅.

Thanks a lot for your detailed description! It was really helpful. I decided to fix it by myself because the part that needs to be rewritten is quite complicated and may take too much time to understand it.

I will release a new patch version soon.

**Comment by JohnnyLAmpAz** [comment]
Checked if on folder page everything was ok but found this behavior again.

![screen](https://user-images.githubusercontent.com/29355695/202207836-4729c53c-09e3-42dc-84e2-44d3de389d80.jpeg)

Both tested on latest v0.2.1 and v0.2.0.

I also noticed that, at least on my university Moodle layout, there is a button in the bottom of the folder view page to download the entire folder, which generates a zip file preserving the internal file structure of the folder itself.

So i think no big problem here because one can directly use that button to download the folder. I think that in order to fix this we need to prevent crawling on the bottom links to other folder, like you said:
> I assume the problem would be that inside the page of a folder, there is another folder link. So the extension will keep crawling into that folder, and thus, think that one should contain the other.

But now from course page after last fix is ok except it doesn't create subfolders obviously.

**Comment by rssws** [comment]
Subfolder is not added as part of the file path. This is not due to the crawling order. Subfolder in moodle has no real link to it, and thus, not crawled. 
A fix could be to parse the html and get the folder structure, then add it to the path. You can have a look at `getMoodleFiles()` function. But I am afraid supporting this would introduce too much complexity.

**Comment by JohnnyLAmpAz** [comment]
> Subfolder is not added as part of the file path. This is not due to the crawling order. Subfolder in moodle has no real link to it, and thus, not crawled.

I think that a solution to this, and in general when you are in a folder, is to just fetch the zip generated from Moodle and give directly that as your output. For example, if you want to download folder at `https://<your_moodle>/mod/folder/view.php?id=<folder_id>`, just fetch it from `https://<your_moodle>/mod/folder/download_folder.php?id=<folder_id>`. This has the benefit to preserve folder file structure, subfolders included! And less work too.

To prevent crawling next and previous resource in folder view I opened #21 with my easy fix for the situation encountered above.

**Comment by rssws** [comment]
You are right about the download button. I think it is available in many moodle variants. Using this link would indeed help preserve the folder structure. However, the link provides a `zip` file, which would make the situation a bit more complicated if the crawler starts from a course view instead of a folder view. In this case, it is hard to decide whether we should unzip the file. Adding the unzipped files to the previous path is definitely possible, but I find it a bit chaotic to implement. Maybe you can think of a neat way of doing that. 

Also, I am not sure if it is worth the effort since users can always simply use the download button from moodle. 😄

**Comment by rssws** [comment]
Btw, it would be nice if separate concerns can be raised in different issues. Feel free to open new issues if they can be handled independently for better reference.

**Comment by JohnnyLAmpAz** [comment]
Sorry for mixing, got that for next time.

I think that when the crawler reaches a folder he could just download the zip of it and extract in the relative path. I would use it both starting from course and folder, because the folder structure isn't preserved also when starting from course root and it would be nice have it.

That being said, I didn't quite get the full logic behind your crawler, gotta think a bit on that before planning on a solution.

**Comment by JohnnyLAmpAz** [comment]
#21 fixed the issue.
